import { useState } from 'react';
import { showNotification } from './NotificationSystem';

function PDFReportGenerator({ user, investments = [], transactions = [] }) {
  const [generating, setGenerating] = useState(false);
  const [reportType, setReportType] = useState('investment');
  const [dateRange, setDateRange] = useState('monthly');

  const generateReport = async () => {
    setGenerating(true);
    
    try {
      // Simulate report generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Create mock PDF content
      const reportData = {
        user: user,
        reportType: reportType,
        dateRange: dateRange,
        generatedAt: new Date().toISOString(),
        investments: investments,
        transactions: transactions,
        summary: {
          totalInvested: investments.reduce((sum, inv) => sum + inv.amount, 0),
          totalProfit: investments.reduce((sum, inv) => sum + inv.profit, 0),
          activeInvestments: investments.filter(inv => inv.status === 'active').length,
          roi: investments.length > 0 ? (
            (investments.reduce((sum, inv) => sum + inv.profit, 0) / 
             investments.reduce((sum, inv) => sum + inv.amount, 0)) * 100
          ).toFixed(2) : 0
        }
      };

      // In a real application, this would use a PDF library like jsPDF
      downloadMockPDF(reportData);
      
      showNotification('success', `${reportType.charAt(0).toUpperCase() + reportType.slice(1)} report downloaded successfully!`);
      
    } catch (error) {
      showNotification('error', 'Failed to generate report. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const downloadMockPDF = (data) => {
    // Create a mock PDF content as text file for demonstration
    const content = `
KLEVERSCAPE INVESTMENT REPORT
=============================

Report Type: ${data.reportType.toUpperCase()}
Date Range: ${data.dateRange.toUpperCase()}
Generated: ${new Date(data.generatedAt).toLocaleString()}
User: ${data.user?.username || 'Demo User'}

INVESTMENT SUMMARY
==================
Total Invested: $${data.summary.totalInvested.toFixed(2)}
Total Profit: $${data.summary.totalProfit.toFixed(2)}
Active Investments: ${data.summary.activeInvestments}
ROI: ${data.summary.roi}%

DETAILED INVESTMENTS
====================
${data.investments.map(inv => `
Investment ID: ${inv.id}
Plan: ${inv.plan}
Amount: $${inv.amount.toFixed(2)}
Profit: $${inv.profit.toFixed(2)}
Status: ${inv.status.toUpperCase()}
Start Date: ${inv.startDate}
`).join('')}

RECENT TRANSACTIONS
===================
${data.transactions.slice(0, 10).map(tx => `
Date: ${tx.date}
Type: ${tx.type}
Amount: $${tx.amount.toFixed(2)}
Status: ${tx.status}
`).join('')}

This report was generated by Kleverscape Investment Platform.
For support, contact: support@kleverscape.com

© 2024 Kleverscape. All rights reserved.
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `kleverscape-${data.reportType}-report-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const reportTypes = [
    { id: 'investment', name: 'Investment Report', icon: '📊', description: 'Detailed investment performance and portfolio analysis' },
    { id: 'transaction', name: 'Transaction History', icon: '📋', description: 'Complete transaction history and account activity' },
    { id: 'tax', name: 'Tax Report', icon: '📄', description: 'Tax-ready document with gains/losses calculation' },
    { id: 'comprehensive', name: 'Comprehensive Report', icon: '📖', description: 'Complete account overview with all activities' }
  ];

  const dateRanges = [
    { id: 'weekly', name: 'Last Week' },
    { id: 'monthly', name: 'Last Month' },
    { id: 'quarterly', name: 'Last Quarter' },
    { id: 'yearly', name: 'Last Year' },
    { id: 'all', name: 'All Time' }
  ];

  return (
    <div className="pdf-report-generator">
      <div className="generator-header">
        <div className="header-info">
          <h3>📄 Investment Reports</h3>
          <p>Generate detailed PDF reports of your investment activity</p>
        </div>
        <div className="generator-status">
          <span className="status-indicator online">
            🟢 PDF Generator Online
          </span>
        </div>
      </div>

      <div className="report-options">
        <div className="option-group">
          <h4>📋 Report Type</h4>
          <div className="report-type-grid">
            {reportTypes.map(type => (
              <div 
                key={type.id}
                className={`report-type-card ${reportType === type.id ? 'selected' : ''}`}
                onClick={() => setReportType(type.id)}
              >
                <div className="type-icon">{type.icon}</div>
                <div className="type-info">
                  <h5>{type.name}</h5>
                  <p>{type.description}</p>
                </div>
                <div className="type-selector">
                  {reportType === type.id ? '✅' : '⚪'}
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="option-group">
          <h4>📅 Date Range</h4>
          <div className="date-range-options">
            {dateRanges.map(range => (
              <button
                key={range.id}
                className={`range-btn ${dateRange === range.id ? 'active' : ''}`}
                onClick={() => setDateRange(range.id)}
              >
                {range.name}
              </button>
            ))}
          </div>
        </div>

        <div className="option-group">
          <h4>📈 Report Preview</h4>
          <div className="report-preview">
            <div className="preview-item">
              <span className="preview-label">Investments Included:</span>
              <span className="preview-value">{investments.length} items</span>
            </div>
            <div className="preview-item">
              <span className="preview-label">Date Range:</span>
              <span className="preview-value">{dateRanges.find(r => r.id === dateRange)?.name}</span>
            </div>
            <div className="preview-item">
              <span className="preview-label">Report Type:</span>
              <span className="preview-value">{reportTypes.find(r => r.id === reportType)?.name}</span>
            </div>
            <div className="preview-item">
              <span className="preview-label">Total Value:</span>
              <span className="preview-value">
                ${investments.reduce((sum, inv) => sum + inv.amount + inv.profit, 0).toFixed(2)}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="generator-actions">
        <div className="action-info">
          <div className="info-item">
            <span className="info-icon">🔒</span>
            <span>Secure PDF generation with encrypted data</span>
          </div>
          <div className="info-item">
            <span className="info-icon">📱</span>
            <span>Compatible with all devices and tax software</span>
          </div>
          <div className="info-item">
            <span className="info-icon">⚡</span>
            <span>Instant download, no email required</span>
          </div>
        </div>

        <button
          className="btn btn-success generate-btn"
          onClick={generateReport}
          disabled={generating}
        >
          {generating ? (
            <>
              <span className="loading-spinner spinner-small"></span>
              Generating Report...
            </>
          ) : (
            <>
              📄 Generate & Download PDF
            </>
          )}
        </button>
      </div>

      {generating && (
        <div className="generation-progress">
          <div className="progress-bar">
            <div className="progress-fill"></div>
          </div>
          <div className="progress-steps">
            <div className="step active">📊 Collecting data</div>
            <div className="step active">🔄 Processing transactions</div>
            <div className="step active">📄 Generating PDF</div>
            <div className="step">📥 Preparing download</div>
          </div>
        </div>
      )}

      <div className="generator-footer">
        <div className="footer-note">
          <span className="note-icon">💡</span>
          <span>
            All reports are generated securely and never stored on our servers. 
            Your financial data remains private and confidential.
          </span>
        </div>
      </div>
    </div>
  );
}

export default PDFReportGenerator;
